### ISSUE TITLE
seção clientes

### ISSUE THREAD

**Issue by afraniomedeiros** [Contemplecom/cg-app#20]
afastar mais as aspas (pode alinhar com as extremidades daquela linha de cima) pq o primeiro depoimento ta ficando em cima da img

**Comment by luandro** [comment]
> o primeiro depoimento ta ficando em cima da img

screenshot por obséquio.

**Comment by afraniomedeiros** [comment]
![screen](https://cloud.githubusercontent.com/assets/21957000/22248664/d4ede1a6-e226-11e6-8975-ac97fbaaf055.PNG)
