### ISSUE TITLE
seção "missão, visão, valores"

### ISSUE THREAD

**Issue by afraniomedeiros** [Contemplecom/cg-app#21]
eu testei aqui e o bug realmente ta loco
o comentário dele no email foi esse:

" quando colocamos o mouse sobre a missão e valores ele se move mas quado colocamos sobre a visão nada acontece ( falta um comando para ele subir)"

**Comment by luandro** [comment]
Testado no Mac e no Windows 7, não consigo replicar o erro pra tentar resolver...
