### ISSUE TITLE
Criar nova pagina com arquivo do blog

### ISSUE THREAD

**Issue by afraniomedeiros** [Contemplecom/cg-app#26]
- adicionar a opção de passar para os lados e ver os textos anteriores.. como está agora só da pra ver 3 textos (último) e pronto

**Comment by luandro** [comment]
Vou adicionar uma pagina de arquivo, com todos os posts.

**Comment by afraniomedeiros** [comment]
maxo, eles pediram pra ter a opção na pag. inicial de ver posts antigos.. acho que o que fica menos bagunçado é essa opção de passar para o lado, tipo um "corrousel" vou colocar um print da ref.

![capturar](https://cloud.githubusercontent.com/assets/21957000/22866736/4de26ea2-f162-11e6-82b8-15b4a1706063.PNG)
