### ISSUE TITLE
integração com o facebook

### ISSUE THREAD

**Issue by afraniomedeiros** [Contemplecom/cg-app#27]
está bugado. vou postar duas fotos uma de como era (padrão) e outra de como está.

![whatsapp image 2017-02-01 at 17 57 13](https://cloud.githubusercontent.com/assets/21957000/22566224/3652d1c0-e972-11e6-835f-c2601724d8a1.jpeg)
![whatsapp image 2017-02-01 at 17 59 55](https://cloud.githubusercontent.com/assets/21957000/22566225/36533ea8-e972-11e6-8382-18d79d4af60b.jpeg)

**Comment by afraniomedeiros** [comment]
testei aqui e ele ainda tá bugado.
vou printar pra tu ver como tá

![capturzar](https://cloud.githubusercontent.com/assets/21957000/22866754/855d2dd6-f162-11e6-9c98-5f57e6f150ac.PNG)

**Comment by luandro** [comment]
Da uma olhada no [debugger](https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fwww.consultoriacg.com.br%2Fpost%3Fp%3Dtimeshare-a-valvula-de-escape-da-hotelaria) do Facebook. Talvez demore um pouco pra atualizar no site mesmo.

**Comment by afraniomedeiros** [comment]
- ta rolando algum problema de sincronização.
no próprio debugger do fb, eu testei outros links.
uns chamam todas as infos, outros chamam só foto e título[sem o description], outros chamam só titulo e descrição(sem foto).

tem como ver isso?

![capturar](https://cloud.githubusercontent.com/assets/21957000/23144545/1dd579f2-f7a7-11e6-8f05-ab23ae917303.PNG)

**Comment by luandro** [comment]
![screen shot 2017-02-20 at 20 13 31](https://cloud.githubusercontent.com/assets/693728/23144833/29b42622-f7a9-11e6-99ee-de07e71f1019.png)

As tags tão todas aí certinho. Vo tentar achar se o Facebook cria algum conflito.
