### ISSUE TITLE
seção "time"

### ISSUE THREAD

**Issue by afraniomedeiros** [Contemplecom/cg-app#3]
- mudar completamente a seção com referência ao site "instituto aquila"
- a seção será uma cópia tal qual, alterando apenas a cor do fundo para o nosso laranja
- colocar em negrito e laranja as iniciais PDCA da parte "valores"

**Comment by luandro** [comment]
- Precisa ajustar o tamanho do fundo do texto
- precisa mudar o texto das metodologias no WP de "string" para "html"

**Comment by afraniomedeiros** [comment]
como é que faz isso home de deus?

**Comment by luandro** [comment]
> precisa mudar o texto das metodologias no WP de "string" para "html"

Feito, só precisar editar no WP.

**Comment by afraniomedeiros** [comment]
Maxo, não consegui inserir html no parte do PDCA.
vc poderia fazer ?

**Comment by luandro** [comment]
Feito!
