### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by afraniomedeiros** [Contemplecom/cg-app#35]
- os posts compartilhados no facebook estão indo com o link do WP
"admin.cgconsultoria.com/post"
quando a pessoa acessa o link, acaba caindo na pag do WP que não está na configuração do site e sim do WP puro

Sugestão: o nativo do wp é dominio.com/wp-admin
talvez locando assim ele chame apenas o post.

**Comment by luandro** [comment]
Da pra tentar alguma coisa com o [plugin de redirecionamento](http://admin.consultoriacg.com.br/wp-admin/tools.php?page=redirection.php)...

**Comment by luandro** [comment]
Buscando solução [aqui](http://stackoverflow.com/questions/40785301/proxy-a-wordpress-install-and-a-nodejs-app-with-nginx-to-the-same-domain)
