### ISSUE TITLE
definir link

### ISSUE THREAD

**Issue by afraniomedeiros** [Contemplecom/cg-app#38]
definir o link como "www.cg.....com"
acho que no wordpress está sem o "www" só com o "http" o problema disso é que eles disseram que algumas vezes tentaram entrar com o www e o site ficava absurdamente lento.
não consegui fazer qualquer link entre as situações, mas se tiver como definir o padrão com o "www" fica melhor.
achei que isso poderia ser feito no WP mas decidi não mexer pra nao cagar nada

**Comment by luandro** [comment]
Minha internet é uma bosta e não muda nada
