### ISSUE TITLE
seção método

### ISSUE THREAD

**Issue by afraniomedeiros** [Contemplecom/cg-app#4]
- adicionar acima da seção um título "como vamos ajudar a sua organização a alcançar resultados? "
- título simples igual do "nossos clientes"
- retirar botão de ação no "on-mouse"
- o texto só deve aparecer com o mouse em cima.

**Comment by luandro** [comment]
Só precisa atualizar o HTML no WP, para ter o negrito no "PDCA", não consigo (Bug??).

**Comment by afraniomedeiros** [comment]
- corrigir o bug do grid
![capturarw](https://cloud.githubusercontent.com/assets/21957000/21629656/7d8f3286-d211-11e6-8472-e82e000ddc0c.PNG)
