### ISSUE TITLE
seção "cursos e treinamentos"

### ISSUE THREAD

**Issue by afraniomedeiros** [Contemplecom/cg-app#6]
- adicionar fundo à seção (img link -> http://cg.luandro.com/wp-content/uploads/2016/12/fundoCG.jpg)
-- overlay laranja 60% na img

- Corrigir a função de texto que é igual as seções acima e não está chamando os textos do WP

**Comment by luandro** [comment]
>    Corrigir a função de texto que é igual as seções acima e não está chamando os textos do WP


Mudado "descrição" para "descricao" no WP, custom fields.

**Comment by afraniomedeiros** [comment]
não estão aparecendo as lacunas no WP pra inserir os textos. :O

**Comment by luandro** [comment]
Atualizado, só precisa colocar o conteúdo novamente.
