### ISSUE TITLE
seção deseja fazer um teste

### ISSUE THREAD

**Issue by afraniomedeiros** [Contemplecom/cg-app#9]
- ajustar o texto ao botão (centralizar)
- botão não funfa

**Comment by luandro** [comment]
Botão ja está centralizado. Link deveria estar funcionando, mas não consigo atualizar WP (bug??).

**Comment by afraniomedeiros** [comment]
os 3 botões estão tipo bloqueados.. não levam a lugar nenhum;

**Comment by luandro** [comment]
Resolvido!
